---
# EN: You can choose between CPU and GPU. (CPU is default)
# VI: Giá trị của HardwareType là CPU hoặc GPU . (Mặc định là CPU)
HardwareType: CPU

# EN: Delay between per checking time (in milisecond). Too low will make your CPU work more. Recomend value: 500 ~ 2500
# VI: Khoảng thời gian giữa mỗi lần check nhiệt độ (đơn vị mili giây). Quá thấp sẽ khiến của bạn hoạt động nhiều hơn. Giá trị khuyến nghị: 2500 ~ 5000
DelayBetweenCheck: 2500

# EN: You can add more temperature miles by adding the following template in TemperatureConfigs section.
# VI: Bạn có thể thêm mốc nhiệt độ đổi màu bằng cách thêm template bên dưới vào trong TemperatureConfigs.
# -Temperature : 50
# Color: 828282
TemperatureConfigs:
- Temperature: 40
  Color: 0044ff
- Temperature: 65
  Color: 00ff00
- Temperature: 80
  Color: ff3c00
